"""Initial tables for Camera, Track, and Observation

Revision ID: d2c6fb626a66
Revises: 
Create Date: 2026-09-05 11:58:35.962941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c6fb626a66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('local_track_id', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.Float(), nullable=True),
    sa.Column('last_seen', sa.Float(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('vehicle_color', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_camera_id'), 'tracks', ['camera_id'], unique=False)
    op.create_index(op.f('ix_tracks_id'), 'tracks', ['id'], unique=False)
    op.create_index(op.f('ix_tracks_local_track_id'), 'tracks', ['local_track_id'], unique=False)
    op.create_table('plate_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('plate_text_raw', sa.String(), nullable=True),
    sa.Column('plate_number_normalized', sa.String(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('plate_detection_confidence', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plate_observations_id'), 'plate_observations', ['id'], unique=False)
    op.create_index(op.f('ix_plate_observations_plate_number_normalized'), 'plate_observations', ['plate_number_normalized'], unique=False)
    op.create_index(op.f('ix_plate_observations_timestamp'), 'plate_observations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_plate_observations_track_id'), 'plate_observations', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plate_observations_track_id'), table_name='plate_observations')
    op.drop_index(op.f('ix_plate_observations_timestamp'), table_name='plate_observations')
    op.drop_index(op.f('ix_plate_observations_plate_number_normalized'), table_name='plate_observations')
    op.drop_index(op.f('ix_plate_observations_id'), table_name='plate_observations')
    op.drop_table('plate_observations')
    op.drop_index(op.f('ix_tracks_local_track_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_camera_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
