"""Add global Vehicle and VehicleObservation tables

Revision ID: df583d405925
Revises: d2c6fb626a66
Create Date: 2026-09-05 13:10:02.756719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df583d405925'
down_revision: Union[str, None] = 'd2c6fb626a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.Column('plate_confidence', sa.Float(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('vehicle_color', sa.String(), nullable=True),
    sa.Column('first_seen', sa.Float(), nullable=True),
    sa.Column('last_seen', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=False)
    op.create_table('vehicle_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id')
    )
    op.create_index(op.f('ix_vehicle_observations_id'), 'vehicle_observations', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_observations_timestamp'), 'vehicle_observations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_vehicle_observations_vehicle_id'), 'vehicle_observations', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_observations_vehicle_id'), table_name='vehicle_observations')
    op.drop_index(op.f('ix_vehicle_observations_timestamp'), table_name='vehicle_observations')
    op.drop_index(op.f('ix_vehicle_observations_id'), table_name='vehicle_observations')
    op.drop_table('vehicle_observations')
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
